version: "3.2"

networks:
  metrics:


services:
  # rbencheikh-esb:
  # container_name: rbencheikh-esb
  # image: rbencheikh/esb
  #  ports:
  #   - 8091:8091
  #  networks:
  #    - metrics

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.console.libraries=/usr/share/prometheus/console_libraries
      - --web.console.templates=/usr/share/prometheus/consoles
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - metrics

  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ALLOW_EMBEDDING=true  # Enable embedding
      - GF_AUTH_ANONYMOUS_ENABLED=true    # Enable anonymous access
      - GF_AUTH_ANONYMOUS_ORG_NAME=Main Org.  # Set the organization name
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Viewer # Set the role for anonymous users
    networks:
      - metrics