eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  application:
    name: gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: users
          uri: http://localhost:8090
          predicates:
            - Path=/api/v1/users/**
        - id: messages
          uri: http://localhost:8091
          predicates:
            - Path=/messages/**
        - id: transformation
          uri: http://localhost:8091
          predicates:
            - Path=/api/messages/**
