eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8092

spring:
  application:
    name: transformation

management :
  endpoints:
    web:
      exposure:
        include:
          - info
          - health

